-- MySQL Script generated by MySQL Workbench
-- Tue May  9 17:34:40 2017
-- Model: Sakila Full    Version: 2.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema pw_system
-- -----------------------------------------------------
-- 个人网站数据库
DROP SCHEMA IF EXISTS `pw_system` ;

-- -----------------------------------------------------
-- Schema pw_system
--
-- 个人网站数据库
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pw_system` DEFAULT CHARACTER SET utf8 ;
USE `pw_system` ;

-- -----------------------------------------------------
-- Table `pw_system`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pw_system`.`user` ;

CREATE TABLE IF NOT EXISTS `pw_system`.`user` (
  `user_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL COMMENT '登录用户名',
  `password` VARCHAR(45) NOT NULL COMMENT '登录密码',
  `user_type` TINYINT(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT '用户类型\n    value:1， 管理员\n    value:0， 普通用户',
  `reg_datetme` DATE NOT NULL,
  `user_email` VARCHAR(45) NOT NULL,
  `head_protrait` VARCHAR(45) NULL COMMENT '头像图片存储路径',
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pw_system`.`article`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pw_system`.`article` ;

CREATE TABLE IF NOT EXISTS `pw_system`.`article` (
  `article_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NOT NULL COMMENT '文章标题',
  `content` MEDIUMTEXT NULL COMMENT '文章内容',
  `create_date` DATE NOT NULL COMMENT '创建日期',
  `state` TINYINT(1) NOT NULL DEFAULT 1 COMMENT '文章状态：\n    value: 1， 正常状态（可读、写）\n    value: 0， 待删除状态（只读）',
  `user_user_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`article_id`),
  INDEX `fk_article_user1_idx` (`user_user_id` ASC),
  CONSTRAINT `fk_article_user1`
    FOREIGN KEY (`user_user_id`)
    REFERENCES `pw_system`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pw_system`.`pictrue`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pw_system`.`pictrue` ;

CREATE TABLE IF NOT EXISTS `pw_system`.`pictrue` (
  `picture_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `url` VARCHAR(100) NOT NULL COMMENT '存储路径',
  `desc` VARCHAR(45) NULL COMMENT '对图片的简短描述',
  `upload_date` DATE NOT NULL COMMENT '上传日期',
  `user_user_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`picture_id`),
  INDEX `fk_pictrue_user_idx` (`user_user_id` ASC),
  CONSTRAINT `fk_pictrue_user`
    FOREIGN KEY (`user_user_id`)
    REFERENCES `pw_system`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pw_system`.`tag`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pw_system`.`tag` ;

CREATE TABLE IF NOT EXISTS `pw_system`.`tag` (
  `tag_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `tag_name` VARCHAR(45) NOT NULL,
  `tag_desc` VARCHAR(45) NOT NULL,
  `tag_type` INT(1) NOT NULL COMMENT '表示此tag的类型\n    value: 1， 文章\n    value: 2， 图片\n    value: 3， 游戏',
  PRIMARY KEY (`tag_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pw_system`.`article_tag_mapping`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pw_system`.`article_tag_mapping` ;

CREATE TABLE IF NOT EXISTS `pw_system`.`article_tag_mapping` (
  `article_article_id` INT UNSIGNED NOT NULL,
  `tag_tag_id` INT UNSIGNED NOT NULL,
  INDEX `fk_article_tag_mapping_article1_idx` (`article_article_id` ASC),
  INDEX `fk_article_tag_mapping_tag1_idx` (`tag_tag_id` ASC),
  CONSTRAINT `fk_article_tag_mapping_article1`
    FOREIGN KEY (`article_article_id`)
    REFERENCES `pw_system`.`article` (`article_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_article_tag_mapping_tag1`
    FOREIGN KEY (`tag_tag_id`)
    REFERENCES `pw_system`.`tag` (`tag_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pw_system`.`picture_tag_mapping`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pw_system`.`picture_tag_mapping` ;

CREATE TABLE IF NOT EXISTS `pw_system`.`picture_tag_mapping` (
  `pictrue_picture_id` INT UNSIGNED NOT NULL,
  `tag_tag_id` INT UNSIGNED NOT NULL,
  INDEX `fk_picture_tag_mapping_pictrue1_idx` (`pictrue_picture_id` ASC),
  INDEX `fk_picture_tag_mapping_tag1_idx` (`tag_tag_id` ASC),
  CONSTRAINT `fk_picture_tag_mapping_pictrue1`
    FOREIGN KEY (`pictrue_picture_id`)
    REFERENCES `pw_system`.`pictrue` (`picture_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_picture_tag_mapping_tag1`
    FOREIGN KEY (`tag_tag_id`)
    REFERENCES `pw_system`.`tag` (`tag_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `pw_system`;

DELIMITER $$

USE `pw_system`$$
DROP TRIGGER IF EXISTS `pw_system`.`user_BEFORE_INSERT` $$
USE `pw_system`$$
CREATE DEFINER = CURRENT_USER TRIGGER `pw_system`.`user_BEFORE_INSERT` BEFORE INSERT ON `user` FOR EACH ROW
set NEW.reg_datetime=now();$$


USE `pw_system`$$
DROP TRIGGER IF EXISTS `pw_system`.`article_BEFORE_INSERT` $$
USE `pw_system`$$
CREATE DEFINER = CURRENT_USER TRIGGER `pw_system`.`article_BEFORE_INSERT` BEFORE INSERT ON `article` FOR EACH ROW
set NEW.create_date=now();$$


USE `pw_system`$$
DROP TRIGGER IF EXISTS `pw_system`.`pictrue_BEFORE_INSERT` $$
USE `pw_system`$$
CREATE DEFINER = CURRENT_USER TRIGGER `pw_system`.`pictrue_BEFORE_INSERT` BEFORE INSERT ON `pictrue` FOR EACH ROW
set NEW.upload_date=now();$$


DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
